name: .NET CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
permissions: read-all|write-all


jobs:
  build:
    uses: SAPTeamDEV/Gawe/.github/workflows/dotnet.yml@master
