name: .NET CI

on:
  workflow_dispatch:
    inputs:
      nuget-deploy:
        description: Deploy package to NuGet gallery
        type: boolean
        default: true
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
    
permissions:
  contents:
    write
  packages:
    write
  pull-requests:
    write

jobs:
  build:
    uses: SAPTeamDEV/Gawe/.github/workflows/dotnet.yml@master
    with:
      nuget-deploy: ${{ contains(inputs.nuget-deploy, 'e') }} # a workaround for runs outside of dispatch
    secrets: inherit
