name: .NET CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [Debug, Release]
    uses: SAPTeamDEV/Gawe/.github/workflows/blank.yml@master
    with:
     os: ${{ matrix.os }}
     configuration: ${{ matrix.configuration }}
