name: .NET CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
    
permissions:
  contents:
    write
  packages:
    write
  pull-requests:
    write

jobs:
  build:
    uses: SAPTeamDEV/Gawe/.github/workflows/dotnet.yml@master
    with:
      nuget-deploy: false
    secrets: inherit
