name: .NET CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    uses: SAPTeamDEV/Gawe/.github/workflows/dotnet.yml@master
